<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>线程崩溃后为什么不会导致 JVM 崩溃？ | YUKIPEDIA's blog</title><meta name=keywords content><meta name=description content="线程崩溃后为什么不会导致 JVM 崩溃？ - YUKIPEDIA's blog"><meta name=author content><link rel=canonical href=https://yuk1pedia.github.io/notes/2025-1-15-jvmcrashes/><link crossorigin=anonymous href=/assets/css/stylesheet.8fe10233a706bc87f2e08b3cf97b8bd4c0a80f10675a143675d59212121037c0.css integrity="sha256-j+ECM6cGvIfy4Is8+XuL1MCoDxBnWhQ2ddWSEhIQN8A=" rel="preload stylesheet" as=style><link rel=icon href=https://yuk1pedia.github.io/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://yuk1pedia.github.io/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=https://yuk1pedia.github.io/favicon-32x32.png><link rel=apple-touch-icon href=https://yuk1pedia.github.io/apple-touch-icon.png><link rel=mask-icon href=https://yuk1pedia.github.io/safari-pinned-tab.svg><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><link rel=alternate hreflang=en href=https://yuk1pedia.github.io/notes/2025-1-15-jvmcrashes/><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--code-block-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><meta property="og:url" content="https://yuk1pedia.github.io/notes/2025-1-15-jvmcrashes/"><meta property="og:site_name" content="YUKIPEDIA's blog"><meta property="og:title" content="线程崩溃后为什么不会导致 JVM 崩溃？"><meta property="og:locale" content="zh-cn"><meta property="og:type" content="article"><meta property="article:section" content="notes"><meta property="article:published_time" content="2025-01-15T00:00:00+00:00"><meta property="article:modified_time" content="2025-01-15T00:00:00+00:00"><meta name=twitter:card content="summary"><meta name=twitter:title content="线程崩溃后为什么不会导致 JVM 崩溃？"><meta name=twitter:description content><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Notes","item":"https://yuk1pedia.github.io/notes/"},{"@type":"ListItem","position":2,"name":"线程崩溃后为什么不会导致 JVM 崩溃？","item":"https://yuk1pedia.github.io/notes/2025-1-15-jvmcrashes/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"线程崩溃后为什么不会导致 JVM 崩溃？","name":"线程崩溃后为什么不会导致 JVM 崩溃？","description":"","keywords":[],"articleBody":"要弄明白这个问题，我们从以下几点进行分析：\n线程崩溃后，进程一定会崩溃吗？ 进程是如何崩溃的？——信号机制简介 为什么在 JVM 中线程崩溃不会导致 JVM 进程崩溃？ 线程崩溃后，进程一定会崩溃吗？ 一般来说如果线程是因为非法访问内存引起的崩溃，那么进程肯定会崩溃。这主要是因为在进程中，各个线程的地址空间是共享的，既然是共享，那么某个线程对地址的非法访问就会导致内存的不确定性，进而会影响到其他线程，可能导致一系列严重的后果，于是操作系统干脆让整个进程崩溃。\n在一个进程中，所有的线程共享代码段、数据段、地址空间，文件非法访问内存有以下几种情况：\n针对只读内存写入数据 #include #includ int main() { char *s = \"hello world\"; // 向只读内存写入数据，导致崩溃 s[1] = 'H'; } 访问了进程没有权限访问的地址空间（比如内核空间） #include #includ int main() { int *p = (int *)0xC0000fff; // 针对进程的内核空间写入数据，导致崩溃 *p = 10; } 在 32 位虚拟地址空间中，p 指向的是内核空间\n访问了不存在的内存 #include #includ int main() { int *a = NULL; *a = 1; } 以上错误都是访问内存时的错误，会统一报 Segment Fault 错误，这些都会导致进程崩溃\n进程是如何崩溃的？——信号机制简介 既然线程崩溃后，进程也会崩溃，那进程到底是如何崩溃的呢？其背后的机制是信号。\n如果我们想要杀掉一个正在运行的进程，常常会用到 kill -9 pid 这样的命令，这里的 kill 其实就是给指定 pid 发送终止信号的意思，其中 9 就是信号。\n在 Linux 中可以通过 kill -l 查看所有可用的信号：\n当然发送 kill 信号需要一定权限，否则任何进程都可以通过发信号来终止其他进程，这显然是不合理的。实际上，kill 执行的是系统调用，将控制权转移给了操作系统内核，由内核来给指定的进程发送信号。\n信号背后的机制如下：\nCPU 执行正常的进程指令 调用 kill 系统调用向进程发送信号 进程收到操作系统发的信号，CPU 暂停当前程序运行，并将控制权转交给操作系统 操作系统根据情况执行相应的信号处理程序（函数） 一般执行完信号处理程序逻辑后会让进程退出 注意第五步，如果进程没有注册自己的信号处理函数，那么操作系统会执行默认的信号处理程序（一般最后会让进程退出），但如果注册了，则会执行进程自己的信号处理函数，这样就给了进程一个垂死挣扎的机会，它收到 kill 信号后，可以调用 exit() 来退出，也可以使用其他函数来恢复进程的执行。\n#include #include #include // 进程自定义的信号处理函数 void sigHandler(int sig) { printf(\"Signal %d catched!\\n\", sig); exit(sig); } int main(void) { signal(SIGSEGV, sigHandler); int *p = (int *)0xC0000fff; *p = 10; // 向内核空间写数据，崩溃 } // 以上程序结果输出：Signal 11 catched! 如上述代码，进程注册信号处理函数后，当收到 SIGSEGV 信号后，先执行相关的逻辑再退出\n另外，当进程接收到信号之后也可以不定义自己的信号处理函数，而是选择忽略信号：\n#include #include #include int main(void) { // 忽略信号 signal(SIGSEGV, SIG_IGN); // 产生一个 SIGSEGV 信号 raise(SIGSEGV); printf(\"正常结束\") } 也就是说虽然给进程发送了 kill 信号，但如果进程自己定义了信号处理函数或者无视信号，就有机会逃出生天，当然 kill -9 命令例外，不管进程是否定义了信号处理函数，都会马上被干掉。\n通过这部分的介绍，再回到标题的问题：线程崩溃后为什么不会导致 JVM 崩溃？\n其实是 JVM 自己定义了信号处理函数，这样当发送 kill pid 命令（默认传入 15 也就是 SIGTERM）后，JVM 就可以在信号处理函数中执行一些资源清理之后再调用 exit 退出。\n这种场景显然不能用 kill -9，不然进程被干掉后资源就来不及清除了。\n为什么在 JVM 中线程崩溃不会导致 JVM 进程崩溃？ 这个问题在第二个部分已经得到了解答，那么在 Java 中有哪些是常见的由于非法访问内存而产生的 exception 或 error 呢？比如 StackoverflowError 或者 NPE（NullPointerException），NPE 就是访问了不存在的内存。\n但为什么栈溢出也是非法访问内存呢？这就需要回到操作系统中进程的虚拟空间，也就是共享地址空间。\n现代操作系统为了保护进程之间不受影响，使用了虚拟地址空间来隔离进程，进程的寻址都是针对虚拟地址，每个进程的虚拟空间都是一样的，而线程会共用进程的地址空间。\n以 32 位操作系统为例，其进程的虚拟空间分布如下：\n那么栈溢出是如何发生的？\n进程每调用一个函数，都会分配一个栈帧，然后在栈帧里会分配函数里定义的各种局部变量。\n假设我们调用了一个无限递归的函数，那么操作系统就会持续分配栈帧，但 stack 的大小是有限的，如果无限递归下去，stack 会很快被分配完，此时再调用函数试图继续分配超出 stack 大小的内存，就会发生栈溢出。\n根据上面的阐述，我们就搞清楚了为什么栈溢出和空指针一样，都算非法访问内存。\n","wordCount":"215","inLanguage":"en","datePublished":"2025-01-15T00:00:00Z","dateModified":"2025-01-15T00:00:00Z","mainEntityOfPage":{"@type":"WebPage","@id":"https://yuk1pedia.github.io/notes/2025-1-15-jvmcrashes/"},"publisher":{"@type":"Organization","name":"YUKIPEDIA's blog","logo":{"@type":"ImageObject","url":"https://yuk1pedia.github.io/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://yuk1pedia.github.io/ accesskey=h title="YUKIPEDIA's blog (Alt + H)">YUKIPEDIA's blog</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)" aria-label="Toggle theme">
<svg id="moon" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg>
<svg id="sun" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=https://yuk1pedia.github.io/about title="About me?"><span>About me?</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><h1 class="post-title entry-hint-parent">线程崩溃后为什么不会导致 JVM 崩溃？</h1><div class=post-meta><span title='2025-01-15 00:00:00 +0000 UTC'>January 15, 2025</span></div></header><div class=post-content><p>要弄明白这个问题，我们从以下几点进行分析：</p><ol><li>线程崩溃后，进程一定会崩溃吗？</li><li>进程是如何崩溃的？——信号机制简介</li><li>为什么在 JVM 中线程崩溃不会导致 JVM 进程崩溃？</li></ol><h2 id=线程崩溃后进程一定会崩溃吗>线程崩溃后，进程一定会崩溃吗？<a hidden class=anchor aria-hidden=true href=#线程崩溃后进程一定会崩溃吗>#</a></h2><p>一般来说如果线程是因为非法访问内存引起的崩溃，<strong>那么进程肯定会崩溃</strong>。这主要是因为在进程中，<strong>各个线程的地址空间是共享的</strong>，既然是共享，那么某个线程对地址的非法访问就会导致内存的不确定性，进而会影响到其他线程，可能导致一系列严重的后果，于是操作系统干脆让整个进程崩溃。</p><p><img alt=img loading=lazy src=https://cdn.xiaolincoding.com//mysql/other/17be94f342ea4e49a227b195845880fd.png></p><p>在一个进程中，所有的线程共享代码段、数据段、地址空间，文件非法访问内存有以下几种情况：</p><ol><li>针对只读内存写入数据</li></ol><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-c data-lang=c><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;stdio.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e>#includ&lt;stdlib.h&gt;
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>int</span> <span style=color:#a6e22e>main</span>() {
</span></span><span style=display:flex><span>	<span style=color:#66d9ef>char</span> <span style=color:#f92672>*</span>s <span style=color:#f92672>=</span> <span style=color:#e6db74>&#34;hello world&#34;</span>;
</span></span><span style=display:flex><span>	<span style=color:#75715e>// 向只读内存写入数据，导致崩溃
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>	s[<span style=color:#ae81ff>1</span>] <span style=color:#f92672>=</span> <span style=color:#e6db74>&#39;H&#39;</span>;
</span></span><span style=display:flex><span>}
</span></span></code></pre></div><ol start=2><li>访问了进程没有权限访问的地址空间（比如内核空间）</li></ol><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-c data-lang=c><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;stdio.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e>#includ&lt;stdlib.h&gt;
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>int</span> <span style=color:#a6e22e>main</span>() {
</span></span><span style=display:flex><span>	<span style=color:#66d9ef>int</span> <span style=color:#f92672>*</span>p <span style=color:#f92672>=</span> (<span style=color:#66d9ef>int</span> <span style=color:#f92672>*</span>)<span style=color:#ae81ff>0xC0000fff</span>;
</span></span><span style=display:flex><span>	<span style=color:#75715e>// 针对进程的内核空间写入数据，导致崩溃
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>	<span style=color:#f92672>*</span>p <span style=color:#f92672>=</span> <span style=color:#ae81ff>10</span>;
</span></span><span style=display:flex><span>}
</span></span></code></pre></div><p>在 32 位虚拟地址空间中，p 指向的是内核空间</p><ol start=3><li>访问了不存在的内存</li></ol><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-c data-lang=c><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;stdio.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e>#includ&lt;stdlib.h&gt;
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>int</span> <span style=color:#a6e22e>main</span>() {
</span></span><span style=display:flex><span>	<span style=color:#66d9ef>int</span> <span style=color:#f92672>*</span>a <span style=color:#f92672>=</span> NULL;
</span></span><span style=display:flex><span>	<span style=color:#f92672>*</span>a <span style=color:#f92672>=</span> <span style=color:#ae81ff>1</span>;
</span></span><span style=display:flex><span>}
</span></span></code></pre></div><p>以上错误都是访问内存时的错误，会统一报 <code>Segment Fault</code> 错误，这些都会导致进程崩溃</p><h2 id=进程是如何崩溃的信号机制简介>进程是如何崩溃的？——信号机制简介<a hidden class=anchor aria-hidden=true href=#进程是如何崩溃的信号机制简介>#</a></h2><p>既然线程崩溃后，进程也会崩溃，那进程到底是如何崩溃的呢？其背后的机制是<strong>信号</strong>。</p><p>如果我们想要杀掉一个正在运行的进程，常常会用到 <code>kill -9 pid</code> 这样的命令，这里的 kill 其实就是给指定 pid 发送终止信号的意思，其中 9 就是<strong>信号</strong>。</p><p>在 Linux 中可以通过 <code>kill -l</code> 查看所有可用的信号：</p><p><img alt=img loading=lazy src=https://cdn.xiaolincoding.com//mysql/other/eba4dce5e59442b8b2b24d9e171bab0d.png></p><p>当然发送 kill 信号需要一定权限，否则任何进程都可以通过发信号来终止其他进程，这显然是不合理的。实际上，kill 执行的是<strong>系统调用</strong>，将控制权转移给了操作系统内核，由内核来给指定的进程发送信号。</p><p>信号背后的机制如下：</p><ol><li>CPU 执行正常的进程指令</li><li>调用 kill 系统调用向进程发送信号</li><li>进程收到操作系统发的信号，CPU 暂停当前程序运行，并将控制权转交给操作系统</li><li>操作系统根据情况执行相应的<strong>信号处理程序（函数）</strong></li><li><strong>一般执行完信号处理程序逻辑后会让进程退出</strong></li></ol><p><strong>注意第五步</strong>，如果进程没有注册自己的信号处理函数，那么操作系统会执行默认的信号处理程序（一般最后会让进程退出），但如果注册了，<strong>则会执行进程自己的信号处理函数</strong>，这样就给了进程一个垂死挣扎的机会，它收到 kill 信号后，可以调用 exit() 来退出，<strong>也可以使用其他函数来恢复进程的执行</strong>。</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-c data-lang=c><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;stdio.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;signal.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;stdlib.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>
</span></span><span style=display:flex><span><span style=color:#75715e>// 进程自定义的信号处理函数
</span></span></span><span style=display:flex><span><span style=color:#75715e></span><span style=color:#66d9ef>void</span> <span style=color:#a6e22e>sigHandler</span>(<span style=color:#66d9ef>int</span> sig) {
</span></span><span style=display:flex><span>    <span style=color:#a6e22e>printf</span>(<span style=color:#e6db74>&#34;Signal %d catched!</span><span style=color:#ae81ff>\n</span><span style=color:#e6db74>&#34;</span>, sig);
</span></span><span style=display:flex><span>    <span style=color:#a6e22e>exit</span>(sig);
</span></span><span style=display:flex><span>}
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>int</span> <span style=color:#a6e22e>main</span>(<span style=color:#66d9ef>void</span>) {
</span></span><span style=display:flex><span>    <span style=color:#a6e22e>signal</span>(SIGSEGV, sigHandler);
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>int</span> <span style=color:#f92672>*</span>p <span style=color:#f92672>=</span> (<span style=color:#66d9ef>int</span> <span style=color:#f92672>*</span>)<span style=color:#ae81ff>0xC0000fff</span>;
</span></span><span style=display:flex><span>    <span style=color:#f92672>*</span>p <span style=color:#f92672>=</span> <span style=color:#ae81ff>10</span>; <span style=color:#75715e>// 向内核空间写数据，崩溃
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>}
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#75715e>// 以上程序结果输出：Signal 11 catched!
</span></span></span></code></pre></div><p>如上述代码，进程注册信号处理函数后，当收到 SIGSEGV 信号后，先执行相关的逻辑再退出</p><p>另外，当进程接收到信号之后也可以不定义自己的信号处理函数，而是选择忽略信号：</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-c data-lang=c><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;stdio.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;signal.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e>#include</span><span style=color:#75715e>&lt;stdlib.h&gt;</span><span style=color:#75715e>
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>int</span> <span style=color:#a6e22e>main</span>(<span style=color:#66d9ef>void</span>) {
</span></span><span style=display:flex><span>	<span style=color:#75715e>// 忽略信号
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>	<span style=color:#a6e22e>signal</span>(SIGSEGV, SIG_IGN);
</span></span><span style=display:flex><span>	
</span></span><span style=display:flex><span>	<span style=color:#75715e>// 产生一个 SIGSEGV 信号
</span></span></span><span style=display:flex><span><span style=color:#75715e></span>	<span style=color:#a6e22e>raise</span>(SIGSEGV);
</span></span><span style=display:flex><span>	
</span></span><span style=display:flex><span>	<span style=color:#a6e22e>printf</span>(<span style=color:#e6db74>&#34;正常结束&#34;</span>)
</span></span><span style=display:flex><span>}
</span></span></code></pre></div><p>也就是说虽然给进程发送了 kill 信号，但如果进程自己定义了信号处理函数或者无视信号，就有机会逃出生天，当然 kill -9 命令例外，<strong>不管进程是否定义了信号处理函数，都会马上被干掉</strong>。</p><p>通过这部分的介绍，再回到标题的问题：<strong>线程崩溃后为什么不会导致 JVM 崩溃？</strong></p><p>其实是 JVM 自己定义了信号处理函数，这样当发送 kill pid 命令（默认传入 15 也就是 SIGTERM）后，JVM 就可以在信号处理函数中执行一些资源清理之后再调用 exit 退出。</p><p>这种场景显然不能用 kill -9，不然进程被干掉后资源就来不及清除了。</p><h2 id=为什么在-jvm-中线程崩溃不会导致-jvm-进程崩溃>为什么在 JVM 中线程崩溃不会导致 JVM 进程崩溃？<a hidden class=anchor aria-hidden=true href=#为什么在-jvm-中线程崩溃不会导致-jvm-进程崩溃>#</a></h2><p>这个问题在第二个部分已经得到了解答，那么在 Java 中有哪些是常见的由于非法访问内存而产生的 exception 或 error 呢？比如 StackoverflowError 或者 NPE（NullPointerException），NPE 就是访问了不存在的内存。</p><p>但为什么栈溢出也是非法访问内存呢？<strong>这就需要回到操作系统中进程的虚拟空间</strong>，也就是<strong>共享地址空间</strong>。</p><p>现代操作系统为了保护进程之间不受影响，使用了虚拟地址空间来隔离进程，进程的寻址都是针对虚拟地址，每个进程的虚拟空间都是一样的，<strong>而线程会共用进程的地址空间</strong>。</p><p>以 32 位操作系统为例，其进程的虚拟空间分布如下：</p><p><img alt=img loading=lazy src=https://cdn.xiaolincoding.com//mysql/other/8de250fcb055400c94f95c99712a1158.png></p><p>那么<strong>栈溢出</strong>是如何发生的？</p><p>进程每调用一个函数，都会分配一个栈帧，然后在栈帧里会分配函数里定义的各种局部变量。</p><p>假设我们调用了一个无限递归的函数，那么操作系统就会持续分配栈帧，但 stack 的大小是有限的，如果无限递归下去，stack 会很快被分配完，此时再调用函数试图继续分配超出 stack 大小的内存，就会发生栈溢出。</p><p><img alt=img loading=lazy src=https://cdn.xiaolincoding.com//mysql/other/c54aff1660e34d8a8a83d534c3390954.png></p><p>根据上面的阐述，我们就搞清楚了为什么<strong>栈溢出</strong>和<strong>空指针</strong>一样，都算非法访问内存。</p></div><footer class=post-footer><ul class=post-tags></ul></footer></article></main><footer class=footer><span>&copy; 2025 <a href=https://yuk1pedia.github.io/>YUKIPEDIA's blog</a></span> ·
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
<a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg viewBox="0 0 12 6" fill="currentColor"><path d="M12 6H0l6-6z"/></svg>
</a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script></body></html>